### ISSUE TITLE
How to test this in Unity Editor?

### ISSUE THREAD

**Issue by hungry4grace** [Mukarillo/UnityAudioRecorder#1]
Thanks for sharing this code. I try to run it, but in the Unity Editor run, if I pressed the "button" to record, it just flashes and does not seem to record anything? But if I build and run, then it will ask me for permission to use the microphone, then  it works well on a  my MacBook.

Is there something I need to give permission to run on the Unity Editor itself?

Thanks

David

**Comment by Mukarillo** [comment]
Hey David,

It's being a long time since I look at this project. But after researching a bit, looks like UnityHub does not have the Microphone permission.
[Do you mind following these steps](https://www.reddit.com/r/Ring/comments/ciztw5/ring_macos_app_how_to_make_your_macs_microphone/)

In step 10, you change to this:
`INSERT INTO access VALUES('kTCCServiceMicrophone','com.unity3d.unityhub',0,1,1,NULL,NULL,NULL,'UNUSED',NULL,0,1541440109);`

If it worked, please let me know so I update the readme 👍 

Thanks!

**Comment by hungry4grace** [comment]
Wow! It works!

Many many thanks. I scratched my head for weeks!

So do you think Apple should fix this eventually? Or Unity should fix it?

Anyway, Thanks again,

David

**Comment by Mukarillo** [comment]
I am glad I was able to help :)

I think this issue is more related to how unity deals with the permissions. I also think Microphone is something that is not very used in the engine, so it might take a while for them to solve this.

Thanks for the feedback, later on I will update the read-me file!
